import { Request, Response, NextFunction } from 'express';
import { ethers } from 'ethers';

// Threshold for payload expiry (e.g., 5 minutes)
const MAX_PAYLOAD_AGE_MS = 5 * 60 * 1000;

/**
 * Express Middleware to verify the cryptographic signature of the verification payload.
 * Ensures that the payload was generated by our SDK's specific session and not manually spoofed.
 */
export function verifySignatureMiddleware(req: Request, res: Response, next: NextFunction) {
  const { payload, timestamp, nonce, signature, signerAddress } = req.body;

  if (!payload || !timestamp || !nonce || !signature || !signerAddress) {
    return res.status(400).json({ success: false, error: "Incomplete secure payload" });
  }

  // 1. Check expiration to prevent replay attacks
  const currentTime = Date.now();
  if (currentTime - timestamp > MAX_PAYLOAD_AGE_MS) {
    return res.status(401).json({ success: false, error: "Payload expired" });
  }

  // 2. Prevent replay attacks using nonce
  // In a production environment, we should check a distributed cache (like Redis) 
  // to ensure this nonce hasn't been used recently.
  // const isNonceReused = await redis.get(`nonce_${nonce}`);
  // if (isNonceReused) return res.status(401).json({ error: "Replay attack detected" });
  // await redis.setex(`nonce_${nonce}`, 300, 'used'); // Cache for 5 minutes

  try {
    const payloadString = JSON.stringify(payload);
    const expectedMessage = `PRAMAN_AUTH_VERIFICATION\nPayload:${payloadString}\nTimestamp:${timestamp}\nNonce:${nonce}`;

    // 3. Recover the address from the signature
    const recoveredAddress = ethers.verifyMessage(expectedMessage, signature);

    // 4. Verify it matches the expected signer
    if (recoveredAddress.toLowerCase() !== signerAddress.toLowerCase()) {
      return res.status(403).json({ success: false, error: "Signature verification failed. Payload tampered." });
    }

    // If everything passes, we attach the verified payload to the request object
    // so downstream route handlers can use it securely without re-verifying.
    (req as any).verifiedPayload = payload;
    (req as any).verifiedSigner = recoveredAddress;
    
    next();
  } catch (error) {
    console.error("Signature verification error:", error);
    return res.status(403).json({ success: false, error: "Invalid signature format" });
  }
}
